---
include:
  # process first
  - "config/annotations*.rb"
  - "**/*.rb"
  - "lib/tasks/*.rake"
  - ".git-hooks/**/*.rb"
  - "script/*"
exclude:
  - db/schema.rb
  - spec/**/*
  - test/**/*
  - config/importmap.rb
  - 'config/application.rb'
  - 'config/environments/development.rb'
  - 'config/environments/production.rb'
  - 'config/environments/test.rb'
  - config/puma.rb
  - vendor/**/*
  - ".bundle/**/*"
  - "db/migrate/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck:strong
  - update_errors
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
  - solargraph-rails
max_files: 5000
