---
include:
  # process first
  - "config/annotations*.rb"
  - "**/*.rb"
  - "lib/tasks/*.rake"
  - ".git-hooks/**/*.rb"
  - "script/*"
exclude:
  - db/schema.rb
  - spec/**/*
  - test/**/*
  - config/puma.rb
  - config/importmap.rb
  # I don't know why this fails
  # https://app.circleci.com/pipelines/github/apiology/cookiecutter-rails/178/workflows/20d4f825-50a3-4dc1-8b6d-9a155fc892cc/jobs/375
  - 'config/environments/**.rb'
  - vendor/**/*
  - ".bundle/**/*"
  - "db/migrate/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck:strong
  - update_errors
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
  - solargraph-rails
max_files: 5000
