---
include:
  - "**/*.rb"
  - "lib/tasks/*.rake"
  - ".git-hooks/**/*.rb"
  - "script/*"
exclude:
  - db/schema.rb # generated
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - "db/migrate/**/*" # mostly generated, ritualistic
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck:strong
  - update_errors
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
  - solargraph-rails
max_files: 5000
