# frozen_string_literal: true

source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.2.2"
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"
# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

gem "pry"
gem "pry-rails"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "mdl"
  gem "rspec"
  gem "rspec-rails"
  # ensure version with branch coverage
  gem "simplecov", [">=0.18.0"]
  gem "simplecov-lcov"
  gem "undercover"
  gem "webmock"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false
end

group :development do
  gem "annotate"
  gem "overcommit", [">=0.64.0", "<0.65.0"]
  gem "punchlist", [">=1.3.1"]
  # ensure recent definitions
  gem "rbs"
  gem "rubocop", ["~> 1.52"]
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rake"
  # ensure version with RSpec/VerifiedDoubleReference
  gem "rubocop-rspec", [">=2.10.0"]
  gem "rubocop-rspec_rails"
  # https://github.com/castwide/solargraph/pull/727
  # gem "solargraph", [">=0.50.0"]
  gem "solargraph",
      git: "https://github.com/apiology/solargraph",
      branch: "master"
  gem "solargraph-rails",
      git: "https://github.com/apiology/solargraph-rails",
      branch: "main"
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Highlight the fine-grained location where an error occurred [https://github.com/ruby/error_highlight]
  gem "error_highlight", ">= 0.4.0", platforms: [ :ruby ]
  gem "yard"
end

# ruby-asana gem is pending key bugfixes for checkoff as of
# 2021-07-29:
#
# See
#  https://github.com/Asana/ruby-asana/issues/109
#  https://github.com/Asana/ruby-asana/issues/110
#
gem "asana",
    git: "https://github.com/apiology/ruby-asana",
    branch: "checkoff_fixes"
#   path: "/Users/broz/src/ruby-asana"
# Awaiting merge and release of
# https://github.com/seamusabshere/cache_method/pull/18
gem "cache_method",
    git: "https://github.com/apiology/cache_method",
    branch: "ruby_3_support"
gem "checkoff" # , path: "/Users/broz/src/checkoff"

gem "redis"

# https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp
gem "net-imap", require: false
gem "net-pop", require: false
gem "net-smtp", require: false

# Ruby 3.3 made this a separate gem
gem "ostruct"
