---
version: 2.1

commands:
  run_with_languages:
    description: "Run the given command in an environment that includes relevant langauges in the PATH"
    parameters:
      command:
        type: string
        description: "What command to execute"
      label:
        type: string
        description: "What to label the run"
        default: <<parameters.command>>
    steps:
      - run:
          name: <<parameters.label>>
          command: |
            export PATH="${HOME}/.pyenv/bin:${PATH}"
            export PATH="${HOME}/.rbenv/bin:${HOME}/.rbenv/shims:${PATH}"
            export PATH="${HOME}/project/node_modules/.bin:${PATH}"
            export PATH="$(pwd)/bin:${PATH}"
            eval "$(pyenv init --path)"
            eval "$(pyenv virtualenv-init -)"
            eval "$(rbenv init -)"

            <<parameters.command>>
          environment:
            # https://app.circleci.com/pipelines/github/apiology/cookiecutter-pypackage/4/workflows/29074dc8-944c-4600-8aaa-5116575fed90/jobs/4
            "LC_ALL": "C.UTF-8"
            "LANG": "C.UTF-8"
  set_up_environment:
    description: "Install source environment"
    steps:
      - checkout
      - run:
          name: Update timestamps to original commit time
          command: |
            git ls-tree -r --name-only HEAD | while read filename; do \
              unixtime=$(git log -1 --format="%at" -- "${filename}")
              touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S')
              touch -ht ${touchtime} "${filename}"
            done
      - restore_cache:
          name: Restore rbenv cache
          keys:
            - rbenv-v5-{% raw %}{{ checksum "Gemfile" }}{% endraw %}-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-
            - rbenv-v5-{% raw %}{{ checksum "Gemfile" }}{% endraw %}-
            - rbenv-v5-
            - rbenv-
      - restore_cache:
          name: Restore ruby-types cache
          keys:
            - ruby-types-v1-{% raw %}{{ checksum "Gemfile" }}{% endraw %}-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-
            - ruby-types-v1-{% raw %}{{ checksum "Gemfile" }}{% endraw %}-
            - ruby-types-v1-
            - ruby-types-
      - restore_cache:
          name: Restore pyenv cache
          keys:
            - pyenv-v2-{% raw %}{{ checksum "requirements_dev.txt" }}{% endraw %}-
            - pyenv-v2-
            - pyenv-
      - run:
          name: Initialize packages
          command: |
            # measuring slows down the script - only enable when you
            # want to debug where this is spending time

            # export FIX_SH_TIMING_LOG=/tmp/fix_sh_timing.log

            PATH="$(pwd)/bin:${PATH}"
            export PATH

            './fix.sh'
      - store_artifacts:
          path: /tmp/fix_sh_timing.log
      - save_cache:
          name: 'Save pyenv cache'
          key: pyenv-v2-{% raw %}{{ checksum "requirements_dev.txt" }}{% endraw %}-{% raw %}{{ checksum ".python-version" }}{% endraw %}
          paths:
            - "requirements_dev.txt.installed"
            - "/home/circleci/.cache/pip/wheels"
            - "/home/circleci/.pyenv"
      - save_cache:
          name: 'Save rbenv cache'
          key: rbenv-v5-{% raw %}{{ checksum "Gemfile" }}{% endraw %}-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-{% raw %}{{ checksum ".ruby-version" }}{% endraw %}-{% raw %}{{ checksum "Makefile" }}{% endraw %}-{% raw %}{{ checksum ".circleci/config.yml" }}{% endraw %} # yamllint disable-line rule:line-length
          paths:
            - "Gemfile.lock.installed"
            - 'vendor/.keep'
            - "vendor/bundle"
            - "/home/circleci/.rbenv"
            - ".bundle"
            - "/home/circleci/.cache/rubocop_cache"
            - "/home/circleci/.cache/gem"
            - "/home/circleci/.bundle/cache"
            - ".make/pg_gem_dependencies"
            - ".bundle"
      - run:
          name: Download new circleci tool
          command: |
            curl -fLSs \
            https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
  quality:
    description: "Quality checks"
    steps:
      - set_up_environment
      - run_with_languages:
          label: Run overcommit
          command: |
            # Coax overcommit into working
            git config --global user.email "test@test.test"
            git config --global user.name "Test Test"
            bundle exec overcommit --sign
            bundle exec overcommit --sign pre-commit

            bundle exec overcommit --run
      - run_with_languages:
          label: Run brakeman
          command: |
            bundle exec brakeman --no-pager --force
      - run_with_languages:
          label: Run Rubocop
          command: |
            bundle exec rubocop
      - run_with_languages:
          label: Ratchet rubocop quality
          command: |
            make rubocop-ratchet
  update_dependencies:
    description: "Update dependencies whose build may have triggered this build"
    parameters:
      gems:
        type: string
        description: "Space-separated list of gems to update"
    steps:
      - run_with_languages:
          label: Update dependencies
          command: |
            set -x
            for package in <<parameters.gems>>
            do
              REMOTE_VERSION=$(gem search "${package}" | \
               grep "${package}" | cut -d\( -f2 | cut -d\) -f1)
              BUNDLED_VERSION=$(bundle info "${package}" | \
                 head -1 | cut -d\( -f2 | cut -d\) -f1)
              if [ ${REMOTE_VERSION:?} == ${BUNDLED_VERSION:?} ]
              then
                continue
              fi

              bundle update --conservative "${package}"

              BUNDLED_VERSION=$(bundle info "${package}" | \
                 head -1 | cut -d\( -f2 | cut -d\) -f1)

              if [ ${REMOTE_VERSION:?} == ${BUNDLED_VERSION:?} ]
              then
                continue
              fi

              echo "Waiting for ${package} v${REMOTE_VERSION} to be"\
                   "available..."
              sleep 20
              bundle update "${package}"

              BUNDLED_VERSION=$(bundle info "${package}" | \
                 head -1 | cut -d\( -f2 | cut -d\) -f1)


              if [ ${REMOTE_VERSION:?} != ${BUNDLED_VERSION:?} ]
              then
                >&2 echo "Manually upgrade to ${package}"\
                         "v${REMOTE_VERSION}"
                exit 1
              fi
            done
            make build-typecheck
            if [ -z "$(git status --porcelain Gemfile.lock)" ]
            then
              echo "No updates needed"
              exit 0
            fi
            # Push any dependency gem updates
            git config user.email 'vince@broz.cc'
            git config user.name 'Vince Broz'
            git status
            # bundle exec so that overcommit is used from Gemfile for
            # git hooks
            #
            # https://app.circleci.com/pipelines/github/apiology/"${package}"-rails/806/workflows/40fdf1ef-fa23-421b-a0f1-641ea0ed1641/jobs/1173
            #
            bundle exec overcommit --sign pre-commit
            bundle exec git commit -m "Bump dependency releases" Gemfile.lock || true
            OVERCOMMIT_DEBUG=1 bundle exec git push --set-upstream origin "${CIRCLE_BRANCH:?}"
            echo "Avoiding double build after git push"
            exit 1

jobs:
  quality:
    working_directory: ~/{{cookiecutter.project_slug}}
    docker:
      - image: cimg/base:current
        environment:
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_DATABASE: {{cookiecutter.project_slug}}_test
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_USERNAME: {{cookiecutter.project_slug}}
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_PASSWORD: ""
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_SERVER: localhost
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_PORT: "5432"
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_DATABASE: {{cookiecutter.project_slug}}_dev
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_USERNAME: {{cookiecutter.project_slug}}
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_PASSWORD: ""
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_SERVER: localhost
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_PORT: "5432"
          RAILS_ENV: test
      # https://thoughtbot.com/blog/circleci-2-rails
      - image: postgres:latest
        environment:
          POSTGRES_USER: {{cookiecutter.project_slug}}
          POSTGRES_DB: {{cookiecutter.project_slug}}_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - quality
  build:
    working_directory: ~/{{cookiecutter.project_slug}}
    docker:
      - image: cimg/base:current
        environment:
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_DATABASE: {{cookiecutter.project_slug}}_test
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_USERNAME: {{cookiecutter.project_slug}}
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_PASSWORD: ""
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_SERVER: localhost
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_TEST_DATABASE_PORT: "5432"
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_DATABASE: {{cookiecutter.project_slug}}_dev
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_USERNAME: {{cookiecutter.project_slug}}
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_PASSWORD: ""
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_SERVER: localhost
          {{cookiecutter.project_slug|upper|replace("-", "_")}}_DEV_DATABASE_PORT: "5432"
          RAILS_ENV: test
      # https://thoughtbot.com/blog/circleci-2-rails
      - image: postgres:latest
        environment:
          POSTGRES_USER: {{cookiecutter.project_slug}}
          POSTGRES_DB: {{cookiecutter.project_slug}}_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - set_up_environment
{% if cookiecutter.use_checkoff %}      - when:
          condition:
            equal: [<< pipeline.git.branch >>, "main"]
          steps:
            - update_dependencies:
                gems: checkoff{% endif %}
      - run:
          name: Verify deltas
          command: |
            if ! git diff --exit-code .
            then
              >&2 echo "Please resolve changes to avoid caching difficulties"
              exit 1
            fi
      - run_with_languages:
          label: Typecheck
          command: |
            make citypecheck citypecoverage
      - store_artifacts:
          path: rbi/{{cookiecutter.project_slug}}.rbi
      - save_cache:
          name: 'Save ruby-types cache'
          key: ruby-types-v1-{% raw %}{{ checksum "Gemfile" }}{% endraw %}-{% raw %}{{ checksum "Gemfile.lock" }}{% endraw %}-{% raw %}{{ checksum ".ruby-version" }}{% endraw %}-{% raw %}{{ checksum {% endraw %}"rbi/{{cookiecutter.project_slug}}.rbi" {% raw %}}}{% endraw %}-{% raw %}{{ checksum "Makefile" }}{% endraw %}-{% raw %}{{ checksum ".circleci/config.yml" }}{% endraw %}  # yamllint disable-line rule:line-length
          paths:
            - ".yardoc"
            - "/home/circleci/.cache/solargraph"
            - "/home/circleci/.sorbet-cache"
            - "/home/circleci/.cache/sorbet"
            - "types.installed"
            - "yardoc.installed"
            - "tapioca.installed"
            - "rbi/{{cookiecutter.project_slug}}.rbi"
      - run_with_languages:
          label: Test
          command: |
            # https://thoughtbot.com/blog/circleci-2-rails
            # Wait for DB
            dockerize -wait tcp://localhost:5432 -timeout 1m

            make citest cicoverage
    # This seemed to shave 5ish% of the build time off when added
    resource_class: large

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 6"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - quality
  quality:
    jobs:
      - quality
  build:
    jobs:
      - build
